import type { Article } from "@/lib/sanity";

export const FALLBACK_ARTICLES: Article[] = [
  {
    _id: "1",
    _createdAt: "2024-01-15",
    title: "The Best Travel Credit Cards of 2024: Our Top Picks",
    slug: { current: "best-travel-credit-cards-2024" },
    category: "Travel",
    excerpt:
      "From sign-up bonuses to lounge access, we break down the top travel cards that will transform how you fly. Whether you're a frequent flyer or an occasional vacationer, there's a card that fits your travel style.",
    publishedAt: "2024-01-15",
    featured: true,
    sourceTitle: "NerdWallet — Best Travel Credit Cards",
    sourceUrl: "https://www.nerdwallet.com/best/credit-cards/travel",
  },
  {
    _id: "2",
    _createdAt: "2024-01-10",
    title: "How to Maximize Your Chase Ultimate Rewards Points",
    slug: { current: "maximize-chase-ultimate-rewards" },
    category: "Rewards",
    excerpt:
      "Learn the insider strategies to get 2x, 3x, and even 5x value from your Chase points with transfer partners. The right redemption can make your points worth far more than face value.",
    publishedAt: "2024-01-10",
    featured: true,
    sourceTitle: "The Points Guy — Chase Ultimate Rewards Guide",
    sourceUrl: "https://thepointsguy.com/guide/ultimate-guide-to-chase-ultimate-rewards/",
  },
  {
    _id: "3",
    _createdAt: "2024-01-05",
    title: "Credit Cards for Beginners: Where to Start",
    slug: { current: "credit-cards-for-beginners" },
    category: "Beginners",
    excerpt:
      "New to travel rewards? Here's the step-by-step guide to building your card portfolio the smart way — without hurting your credit score or paying unnecessary fees.",
    publishedAt: "2024-01-05",
    featured: true,
    sourceTitle: "Bankrate — Best Starter Credit Cards",
    sourceUrl: "https://www.bankrate.com/credit-cards/rewards/best-starter-cards/",
  },
  {
    _id: "4",
    _createdAt: "2023-12-28",
    title: "Delta SkyMiles Cards: Which One Is Right for You?",
    slug: { current: "delta-skymiles-cards-comparison" },
    category: "Delta",
    excerpt:
      "The Gold, Platinum, and Reserve all have their place. Here's how to choose based on how often you fly Delta, how much you spend, and whether lounge access is worth the premium.",
    publishedAt: "2023-12-28",
    featured: true,
    sourceTitle: "The Points Guy — Delta SkyMiles Cards Compared",
    sourceUrl: "https://thepointsguy.com/card-comparison/delta-skymiles-credit-cards/",
  },
  {
    _id: "5",
    _createdAt: "2023-12-20",
    title: "The Best Credit Cards for Couples Traveling Together",
    slug: { current: "best-credit-cards-for-couples" },
    category: "Couples",
    excerpt:
      "Two people, two cards, one amazing trip. Pair your cards to maximize every dollar you spend together — and earn enough points for flights and hotels faster than going it alone.",
    publishedAt: "2023-12-20",
    featured: true,
    sourceTitle: "NerdWallet — Best Cards for Couples",
    sourceUrl: "https://www.nerdwallet.com/article/credit-cards/best-credit-cards-couples",
  },
  {
    _id: "6",
    _createdAt: "2023-12-15",
    title: "Airport Lounge Access: The Complete Guide",
    slug: { current: "airport-lounge-access-guide" },
    category: "Travel",
    excerpt:
      "Priority Pass, Centurion Lounges, Delta Sky Club — which cards get you in, and is it worth the annual fee? We break down every major lounge network and the cards that unlock them.",
    publishedAt: "2023-12-15",
    featured: true,
    sourceTitle: "The Points Guy — Airport Lounge Access Guide",
    sourceUrl: "https://thepointsguy.com/guide/airport-lounge-access-credit-cards/",
  },
  {
    _id: "7",
    _createdAt: "2023-12-10",
    title: "Amex Membership Rewards: A Complete Transfer Partner Guide",
    slug: { current: "amex-membership-rewards-transfer-partners" },
    category: "Rewards",
    excerpt:
      "Not all transfer partners are created equal. Here's how to pick the right ones for outsized value on your Amex points — and which airlines and hotels give you the best bang for your points.",
    publishedAt: "2023-12-10",
    featured: false,
    sourceTitle: "The Points Guy — Amex Transfer Partners",
    sourceUrl: "https://thepointsguy.com/guide/amex-membership-rewards-transfer-partners/",
  },
  {
    _id: "8",
    _createdAt: "2023-12-05",
    title: "How to Book International Business Class Using Points",
    slug: { current: "book-international-business-class-with-points" },
    category: "Travel",
    excerpt:
      "Business class doesn't have to cost $8,000. Here's the playbook for using miles to fly flat-bed across the Atlantic — and the specific programs and partner airlines that make it possible.",
    publishedAt: "2023-12-05",
    featured: false,
    sourceTitle: "The Points Guy — Book Business Class With Miles",
    sourceUrl: "https://thepointsguy.com/guide/how-to-book-business-class-award-flights/",
  },
  {
    _id: "9",
    _createdAt: "2023-11-28",
    title: "The 5/24 Rule Explained: What Chase Cardholders Need to Know",
    slug: { current: "chase-5-24-rule-explained" },
    category: "Beginners",
    excerpt:
      "Chase's infamous 5/24 rule can derail your points strategy. Here's everything you need to know to plan around it — including which cards count, which don't, and how to get approved.",
    publishedAt: "2023-11-28",
    featured: false,
    sourceTitle: "NerdWallet — Chase 5/24 Rule Explained",
    sourceUrl: "https://www.nerdwallet.com/article/credit-cards/the-5-24-rule-everything-you-need-to-know",
  },
];

export const FALLBACK_CARD_PICKS = [
  {
    _id: "cp1",
    cardName: "Chase Sapphire Preferred",
    issuer: "Chase",
    category: "Travel",
    tagline: "60,000 bonus points after $4,000 spend. Best-in-class transfer partners.",
    affiliateLink: "#",
    featured: true,
    order: 1,
  },
  {
    _id: "cp2",
    cardName: "Amex Gold Card",
    issuer: "American Express",
    category: "Rewards",
    tagline: "4x points at restaurants & U.S. supermarkets. $120 dining credit.",
    affiliateLink: "#",
    featured: true,
    order: 2,
  },
  {
    _id: "cp3",
    cardName: "Delta SkyMiles Gold Amex",
    issuer: "American Express",
    category: "Delta",
    tagline: "Free checked bag, priority boarding, and 2x miles on Delta purchases.",
    affiliateLink: "#",
    featured: true,
    order: 3,
  },
  {
    _id: "cp4",
    cardName: "Capital One Venture X",
    issuer: "Capital One",
    category: "Travel",
    tagline: "Unlimited 2x miles on everything. $300 travel credit. Airport lounge access.",
    affiliateLink: "#",
    featured: false,
    order: 4,
  },
  {
    _id: "cp5",
    cardName: "Citi Strata Premier",
    issuer: "Citibank",
    category: "Rewards",
    tagline: "3x points on air, hotels, restaurants, groceries & gas. No foreign transaction fees.",
    affiliateLink: "#",
    featured: false,
    order: 5,
  },
  {
    _id: "cp6",
    cardName: "Discover it Miles",
    issuer: "Discover",
    category: "Beginners",
    tagline: "1.5x miles on everything. Discover matches all miles at end of first year.",
    affiliateLink: "#",
    featured: false,
    order: 6,
  },
];
